Horizontal table of contents implementation
ramp4-pcar4/story-ramp pull request #413
Opened 2024-03-14 15:56 UTC by KashishMistry

### Related Item(s)
#402 

### Changes
- Added horizontal table of contents component
- Implementation is such that the config of the project metadata will determine if the table of contents will be horizontal or vertical

### Notes
![horizontaltabs](https://github.com/ramp4-pcar4/story-ramp/assets/83516523/b1e26fd0-7176-4d3d-9d40-ef2725c5bcff)

### Testing
Since the adjacent PR is open in the editor repo, there isn't much to test. With this PR, the vertical table of contents will be shown in the demo as the project metadata config has not been updated in the editor.

2024-03-15 14:47 UTC, yileifeng requested changes
Looks good, just a question but do we want to have the horizontal ToC collapsible? 

Just as a reminder will also need to update the package.json version and publish to NPM once everything is tested and working for the editor preview. 

> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/413#-:-Nt1ZAWw05ziiNyKRdBn:bbz451f)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @KashishMistry)

___
*[`src/components/story/story-content.vue` line 4 at r1](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/413#-Nt1Z1zd1s7Fm8ZavFJA:-Nt1Z1zd1s7Fm8ZavFJB:b-2dmhfs) ([raw file](https://github.com/ramp4-pcar4/story-ramp/blob/bb1b2fd7fd7c5647dba9ee7381fd11be037193a9/src/components/story/story-content.vue#L4)):*
> ```Vue
>     <div class="items-stretch">
>         <!-- :class="{ flex: !$props.config?.tocOrientation || $props.config?.tocOrientation === 'vertical' }" -->
>         <!-- v-if="$props.config?.tocOrientation === 'horizontal'" -->
> ```

Blocking until ready to merge


<!-- Sent from Reviewable.io -->

2024-03-15 14:58 UTC, RyanCoulsonCA requested changes
Awesome work, looks great! I noticed that when you click on one of the chapters part of the content is blocked by the ToC. We may need to tweak the `scrollToChapter` function to account for the height of the ToC element to get around this.

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/413#-:-Nt1a33I9xQEk-cS2HYL:b1qzanm)* status: all files reviewed, 1 unresolved discussion (waiting on @KashishMistry)



<!-- Sent from Reviewable.io -->

2024-03-20 20:07 UTC, KashishMistry reviewed
Donethanks (for the scrolling issue).

> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/413#-:-NtSTSaO4PMiZQxrkunZ:b-bryl2j)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @RyanCoulsonCA)



<!-- Sent from Reviewable.io -->

2024-03-25 13:21 UTC, RyanCoulsonCA approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/413)* status: all files reviewed, 1 unresolved discussion (waiting on @KashishMistry)



<!-- Sent from Reviewable.io -->

2024-03-25 18:22 UTC, KashishMistry commented
Some formatting changes made to align table of contents and set css properties dynamically

2024-03-25 19:26 UTC, yileifeng approved these changes
> Reviewed 1 of 4 files at r1, 3 of 4 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/413)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @KashishMistry)



<!-- Sent from Reviewable.io -->

2024-03-25 19:43 UTC, yileifeng approved these changes
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/413)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @KashishMistry)



<!-- Sent from Reviewable.io -->

2024-03-26 20:25 UTC, dnlnashed approved these changes
> Reviewed 1 of 4 files at r1, 3 of 4 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/413)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @KashishMistry)



<!-- Sent from Reviewable.io -->

2024-03-27 18:59 UTC, yileifeng approved these changes
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/413)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @KashishMistry)



<!-- Sent from Reviewable.io -->

2024-03-27 19:02 UTC, yileifeng requested changes
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/413)* status: all files reviewed, 1 unresolved discussion (waiting on @KashishMistry)

___
*[`src/components/story/story-content.vue` line 3 at r7](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/413#-Nu0H_O4EekSjjKZ3MNV:-Nu0H_O539r0f_B3wiiW:b9a6as0) ([raw file](https://github.com/ramp4-pcar4/story-ramp/blob/91011ca53f6222fc31ac6c7788d5bcc92e636c08/src/components/story/story-content.vue#L3)):*
> ```Vue
> <template>
>     <div class="items-stretch">
>         <!-- :class="{ flex: !$props.config?.tocOrientation || $props.config?.tocOrientation === 'vertical' }" -->
> ```

blocking until merge


<!-- Sent from Reviewable.io -->

2024-03-27 19:02 UTC, RyanCoulsonCA approved these changes
> Reviewed 2 of 4 files at r4, 1 of 1 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/413)* status: all files reviewed, 1 unresolved discussion (waiting on @KashishMistry)



<!-- Sent from Reviewable.io -->

2024-04-02 19:19 UTC, yileifeng approved these changes
> Reviewed 3 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/413)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @KashishMistry)



<!-- Sent from Reviewable.io -->

2024-04-02 19:27 UTC, merged