emit map-created event on map load
ramp4-pcar4/story-ramp pull request #456
Opened 2024-08-13 19:33 UTC by RyanCoulsonCA

### Related Item(s)
Not related to any issue, required for CWS migration.

### Changes
With the way we've implemented Storylines, we don't have any direct way of using custom templates within RAMP. The traditional way of doing this would be to instantiate the map using `const rInstance = createInstance(...)`, and then use rInstance returned from the function to register new Vue templates as such `rInstance.$element.component('new-component', ...)`. 

Since Storylines is instantiating the maps for us, we don't have access to the `rInstance` variable. To solve this, I've added a new `map-created` event which is emitted from the app upon map instantiation that will allow you to register Vue templates on a product host page. 

I've also added a `customTemplates` property to the map panel config so the host page can easily access the custom template names for registration.

Example map config (map0.json, pretend this is an entire map config and not just a layer). Note the custom details template `custom`. 
```json
{ 
  "name": "Project",
  "fixtures": {
    "details": {
      "template": "custom"
    }
  },
  "id": "PP",
  "url": "https://maps-cartes.dev.ec.gc.ca/arcgis/rest/services/CWS_SCF/PriorityPlaces/MapServer/0",
  "layerType": "esri-feature"
}
```

Example Storylines map panel config:
```json
"panel": {
  "config": "map0.json",
  "type": "map",
  "title": "",
  "customTemplates": ["custom"]
}
```

Now, in order to register the custom template, you would put something like this on the host page (index-ca-en.html for example):

```js
 document.addEventListener('map-created', (data) => {
  const details = data.detail;

  if (details.customTemplates && details.customTemplates.length > 0) {
    details.customTemplates.forEach((t) => {
      details.rInstance.$element.component(t, {
        props: ['identifyData', 'fields'],
        template: `<div>I am a custom template. Layer name: {{this.identifyData.data['Name']}}</div>`
        methods: { // any methods you need in the template go here. }
      });
    });
  }
});
```

### Testing
Steps:
1. Load the demo page and open the developer console. Paste the following code block in. When you scroll down to a map, you should see the console.log print in the console.

```js
document.addEventListener('map-created', (data) => {
    console.log("Hello world!", data);
});
```

2024-08-13 19:42 UTC, james-rae commented
Cool stuff.  🤡 question, does it need to be done on the host page due to the template having `methods`, which can't be JSON-ified and thus stored in the config definition?

2024-08-13 19:48 UTC, RyanCoulsonCA commented
It's primarily because we can't execute JavaScript within a JSON file, so we wouldn't be able to access the `rInstance.$element.component()` function that we need to actually register the component.

2024-08-13 19:52 UTC, szczz approved these changes
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/456)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @RyanCoulsonCA)



<!-- Sent from Reviewable.io -->

2024-08-13 19:56 UTC, james-rae commented
> we can't execute JavaScript within a JSON file

was thinking in your `setupMap` method, could do 

```
props.config.realTemplateGutsArray.forEach(template =>
    rInstance.$element.component(keyFromSomewhere, template));
```

where the entire template is mashed into the config. but I suspect the `methods` part won't de-serialize since it's not part of JSON spec.

We might be saying the same thing with different words. ALL GOOD.

2024-08-13 19:58 UTC, RyanCoulsonCA commented
Yup I was about to edit my comment. It would work if we just needed templates, but as soon as we want to add custom `methods` we'd run into issues unless we use our good friend `eval` which I don't think the GitHub security bot would love very much 🤖

2024-08-14 12:40 UTC, yileifeng approved these changes
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/456)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @RyanCoulsonCA)



<!-- Sent from Reviewable.io -->

2024-08-14 13:16 UTC, dnlnashed approved these changes
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/456)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @RyanCoulsonCA)



<!-- Sent from Reviewable.io -->

2024-08-14 13:21 UTC, spencerwahl approved these changes
![image.png](https://files.reviewableusercontent.io/images/reviewable/8732588/jq1gxJ-mjflnE79m4mQGGmUT/image.png)

Seeing these errors in console every time a map is created.

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/456#-:-O4G28aK33C6ObLlK2Hz:bm1fwd6)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @RyanCoulsonCA)



<!-- Sent from Reviewable.io -->

2024-08-14 13:24 UTC, spencerwahl requested changes
Reviewable sneakily marked me as :+1: 

> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/456#-:-O4G2ir90mpmkW6jxaRr:b-pcpi3j)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @RyanCoulsonCA)



<!-- Sent from Reviewable.io -->

2024-08-14 13:36 UTC, RyanCoulsonCA reviewed
I noticed this too. Running the app locally shows a slightly more helpful stack trace, but it strangely seems to be coming entirely from the RAMP4 package:
![image.png](https://files.reviewableusercontent.io/images/reviewable/25874602/GHf-h38M24cKbDsUpzAURZNO/image.png)

It's also only showing up for me for the `00000000-0000-0000-0000-000000000000` product and not on either of the CWS products I'm working on, so there may just be a configuration issue somewhere in that config for that product.

This issue is also occurring on the main branch so it's not caused by this PR, so we should probably throw it into a new issue for investigation.

> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/456#-:-O4G4s3-EYLTshe9OJhs:b-nwcao5)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @RyanCoulsonCA)



<!-- Sent from Reviewable.io -->

2024-08-14 13:55 UTC, RyanCoulsonCA reviewed
Just pushed a fix for an issue with maps with titles not fitting on the screen as well. This was fixed in the past but got overwritten at some point.

Before:
![image copy 2.png](https://files.reviewableusercontent.io/images/reviewable/25874602/Jz3Hd98qepNKqSjhFqSW9TQY/image.png)

After:
![image.png](https://files.reviewableusercontent.io/images/reviewable/25874602/cTqa0GaxCzWDboATGQCHg3tL/image.png)

> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/456#-:-O4G8uBP5dB-57pcyRkA:b-x96kky)* status: 3 of 4 files reviewed, all discussions resolved (waiting on @dnlnashed, @spencerwahl, @szczz, and @yileifeng)



<!-- Sent from Reviewable.io -->

2024-08-14 14:25 UTC, spencerwahl approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/456)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @RyanCoulsonCA)



<!-- Sent from Reviewable.io -->

2024-08-14 17:36 UTC, merged