Rework highlighting for flexible table of contents
ramp4-pcar4/story-ramp pull request #466
Opened 2024-09-13 18:02 UTC by yileifeng

### Related Item(s)
Closes #465 

### Changes
- [FIX] ToC highlighting for customized table of contents menu, will highlight the last slide that exists before current active slide that is part of the ToC menu

### Testing
Scroll around and make sure there is a highlighted ToC section at all times + highlighted section makes logical sense if it active slide is not part of ToC.

2024-09-17 14:00 UTC, RyanCoulsonCA requested changes
It seems like the ToC highlighting isn't working on small screen resolutions (when the mobile bar is visible). None of the hexagons are ever highlighted

> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/466#-:-O7-GusMBsNq7Bje9wP8:b-cdtoup)* status: 0 of 4 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-09-24 18:15 UTC, yileifeng reviewed
Donethanks

> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/466#-:-O7_EhbaAe53lHoFAFhL:bah2568)* status: 0 of 4 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-09-24 18:21 UTC, RyanCoulsonCA approved these changes
> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/466)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yileifeng)



<!-- Sent from Reviewable.io -->

2024-09-25 19:36 UTC, IshavSohal approved these changes
> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/466)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yileifeng)



<!-- Sent from Reviewable.io -->

2024-09-26 14:11 UTC, merged