fix window resizing issues, horizontal scrollbar overlap
ramp4-pcar4/story-ramp pull request #488
Opened 2024-10-15 19:07 UTC by RyanCoulsonCA

### Related Item(s)
#443 

### Changes
- When resizing the product, everything should now reposition and scale correctly instead of displaying a horizontal scrollbar.
- Also fixes an issue where the horizontal table of contents would cover parts of the stickied content.
- Removed the `top-8` and `top-16` classes from panels as they are no longer required.

### Testing
Steps:
1. Open the demo page.
2. Ensure everything is still positioned correctly, and that the right hand stickied content is nicely aligned at the top of the page under the header.
3. Now, resize the window (not to mobile width just yet).
4. Ensure there is no horizontal scrollbar. Check that everything has resized correctly, and that stickied content is still nicely aligned at the top of the page.
5. Make the page mobile width. Do the same checks and make sure everything is nicely positioned.

2024-10-16 19:53 UTC, spencerwahl approved these changes
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/488)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @RyanCoulsonCA)



<!-- Sent from Reviewable.io -->

2024-10-17 13:41 UTC, yileifeng requested changes
Resizing works well across all browsers, but noticed an issue on medium browser resolutions for dynamic panel content getting shrunk due to spacing: 

![image.png](https://files.reviewableusercontent.io/images/reviewable/31557789/dObfd-evDuUso2X97qooFVT-/image.png)

Sometimes the dynamic text content even takes up the entire screen width. 

> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/488#-:-O9Pgs-n4JmRd0ciDf6x:b-m5bh7t)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @RyanCoulsonCA)



<!-- Sent from Reviewable.io -->

2024-10-17 18:43 UTC, RyanCoulsonCA reviewed
> Resizing works well across all browsers, but noticed an issue on medium browser resolutions for dynamic panel content getting shrunk due to spacing:

This is happening because this text side of this dynamic panel has a fixed width of 800px. Looking for a solution to this now.

> Noticed that the transported grid disappears once you enter mobile mode (not sure if this is expected behaviour).

Yeah this is [*temporarily* intentional](https://github.com/ramp4-pcar4/story-ramp/pull/483#issuecomment-2400633883), but we will need to figure something out for this sometime soon. Hopefully tooltip issue will resolve itself once we get the grid showing up on mobile.

> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/488#-:-O9Qm4-S-2sRwh19ZJ4o:bwgjdy1)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @RyanCoulsonCA)



<!-- Sent from Reviewable.io -->

2024-10-18 15:56 UTC, RyanCoulsonCA reviewed
> Resizing works well across all browsers, but noticed an issue on medium browser resolutions for dynamic panel content getting shrunk due to spacing:

Should be fixed now. I've changed the type of the `contentWidth` property from `number` to `string`, which allows us to support percentages instead of a fixed width. Fixed widths will just end up being messy on different screen sizes in the long run.

> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/488#-:-O9VJki784HotdbCY0Bf:b-xzuehq)* status: 8 of 12 files reviewed, all discussions resolved (waiting on @spencerwahl, @szczz, and @yileifeng)



<!-- Sent from Reviewable.io -->

2024-10-18 16:03 UTC, RyanCoulsonCA commented
Also included the fix for #490 in this PR.

2024-10-18 18:18 UTC, yileifeng approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/488#-:-O9VqYCn7KyS8jRb5uC9:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @RyanCoulsonCA)



<!-- Sent from Reviewable.io -->

2024-10-18 20:42 UTC, spencerwahl approved these changes
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/488)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @RyanCoulsonCA)



<!-- Sent from Reviewable.io -->

2024-10-23 15:37 UTC, merged