Handle undefined slides
ramp4-pcar4/story-ramp pull request #500
Opened 2024-11-08 20:34 UTC by gordlin

### Related Item(s)
#496 
Should be used with Storylines Editor ToC PR: https://github.com/ramp4-pcar4/storylines-editor/pull/409

### Changes
- [FEATURE] Allow for undefined slides in Storylines. StoryRAMP will automatically remove these slides before displaying, to prevent crashes.

### Testing
Steps:
1. Use [these instructions](https://github.com/ramp4-pcar4/story-ramp/discussions/398) to use this new code locally.
2. Open a storylines (using the https://github.com/ramp4-pcar4/storylines-editor/pull/409 branch) with undefined slides (e.g. current version of `00000000-0000-0000-0000-000000000000`)
3. Preview the language with undefined slides (french here)
4. See that the storyline preview doesn't crash, and that the undefined slide doesn't show up.

2024-11-08 21:12 UTC, yileifeng requested changes
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/500)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @gordlin)

___
*[`ramp-storylines_demo-scenarios-pcar-3.1.7.tgz` line 0 at r1](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/500#-OBCbDIGCUfXOWYF2EiO:-OBCbDIH9M6Le-AxtQeM:blozv4i) ([raw file](https://github.com/ramp4-pcar4/story-ramp/blob/95291f24459570dc084d06174f9dec125dcf9216/ramp-storylines_demo-scenarios-pcar-3.1.7.tgz#L0)):*
Remove this file from PR, instead update the dependency version in `package.json` and I can either publish to NPM after merge or can give you permissions to contribute to NPM package. 


<!-- Sent from Reviewable.io -->

2024-11-08 22:10 UTC, gordlin reviewed
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/500)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @yileifeng)

___
*[`ramp-storylines_demo-scenarios-pcar-3.1.7.tgz` line  at r1](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/500#-OBCbDIGCUfXOWYF2EiO:-OBCoYahEVsZSUakPRL2:b-66dti3) ([raw file](https://github.com/ramp4-pcar4/story-ramp/blob/95291f24459570dc084d06174f9dec125dcf9216/ramp-storylines_demo-scenarios-pcar-3.1.7.tgz#L)):*
<details><summary><i>Previously, yileifeng (Yi Lei Feng) wrote…</i></summary><blockquote>

Remove this file from PR, instead update the dependency version in `package.json` and I can either publish to NPM after merge or can give you permissions to contribute to NPM package.
</blockquote></details>

Donethanks! Do I update the StoryRAMP dependency version in the Storylines Editor ToC PR too?


<!-- Sent from Reviewable.io -->

2024-11-12 14:58 UTC, yileifeng approved these changes
> Reviewed 1 of 2 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/500)* status: all files reviewed, 1 unresolved discussion (waiting on @gordlin)

___
*[`ramp-storylines_demo-scenarios-pcar-3.1.7.tgz` line  at r1](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/500#-OBCbDIGCUfXOWYF2EiO:-OBVsL1AAABd5NcLkKTb:b37p5cr) ([raw file](https://github.com/ramp4-pcar4/story-ramp/blob/95291f24459570dc084d06174f9dec125dcf9216/ramp-storylines_demo-scenarios-pcar-3.1.7.tgz#L)):*
<details><summary><i>Previously, gordlin (Gordon Lin) wrote…</i></summary><blockquote>

Donethanks! Do I update the StoryRAMP dependency version in the Storylines Editor ToC PR too?
</blockquote></details>

Yep, right after we publish the updated changes to NPM :+1:


<!-- Sent from Reviewable.io -->

2024-11-12 15:06 UTC, RyanCoulsonCA approved these changes
> Reviewed 1 of 2 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/500)* status: all files reviewed, 1 unresolved discussion (waiting on @gordlin)



<!-- Sent from Reviewable.io -->

2024-11-12 16:25 UTC, szczz approved these changes
> Reviewed 1 of 2 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/500)* status: all files reviewed, 1 unresolved discussion (waiting on @gordlin)



<!-- Sent from Reviewable.io -->

2024-11-12 16:50 UTC, merged