Fix mismatch with ToC
ramp4-pcar4/story-ramp pull request #516
Opened 2024-12-09 20:21 UTC by IshavSohal

### Related Item(s)
https://github.com/ramp4-pcar4/storylines-editor/issues/437

### Changes
- Set top position for the scroll behavior of slides such that the slides corresponding ToC icon is highlighted (rather than the subsequent icon)

### Testing
Steps:
1. Open a product with a vertical ToC
2. Scroll through the slides, and ensure that the correct ToC icon is highlighted
3. Click on the ToC icons and ensure that they are highlighted (rather than the subsequent icon)
4. Decrease the screen width and repeat steps 2-3

2024-12-18 19:01 UTC, RyanCoulsonCA requested changes
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/516)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @IshavSohal)

___
*[`src/router/index.ts` line 28 at r1](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/516#-OEQ64Mp87geCapM-9lY:-OEQ64Mp87geCapM-9lZ:brgvdc9) ([raw file](https://github.com/ramp4-pcar4/story-ramp/blob/85e3b6015b206264f14af588cc1cba5c4ba975a3/src/router/index.ts#L28)):*
> ```XML
>                 el: decodeURIComponent(to.hash),
>                 behavior: 'smooth',
>                 top: window.innerHeight / 6
> ```

This seems to fix the issue, but I'm wondering if there's maybe a way to fix this problem by adjusting the `activeChapterIndex` logic instead? There are some fancy calculations being done [here](https://github.com/ramp4-pcar4/story-ramp/blob/main/src/components/story/story-content.vue#L143), which is what we use to determine which chapter is currently active (and therefore which ToC entry is highlighted). Maybe playing around with this logic may also fix the problem?

EDIT: The scrollama component in the same file also supports a [`threshold` property](https://github.com/ramp4-pcar4/story-ramp/blob/main/src/components/story/story-content.vue#L143) that may be useful to play around with as well.

The previous `top` value calculation was just added [about a month ago](https://github.com/ramp4-pcar4/story-ramp/pull/502) to fix an issue where clicking on a ToC entry wouldn't take the user to the top of a slide, which this new calculation re-introduces.


<!-- Sent from Reviewable.io -->

2025-01-03 18:12 UTC, IshavSohal reviewed
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/516)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @RyanCoulsonCA)

___
*[`src/router/index.ts` line 28 at r1](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/516#-OEQ64Mp87geCapM-9lY:-OFhLRm74791YZ9Ya7OE:beuwbke) ([raw file](https://github.com/ramp4-pcar4/story-ramp/blob/85e3b6015b206264f14af588cc1cba5c4ba975a3/src/router/index.ts#L28)):*
<details><summary><i>Previously, RyanCoulsonCA (Ryan Coulson) wrote…</i></summary><blockquote>

This seems to fix the issue, but I'm wondering if there's maybe a way to fix this problem by adjusting the `activeChapterIndex` logic instead? There are some fancy calculations being done [here](https://github.com/ramp4-pcar4/story-ramp/blob/main/src/components/story/story-content.vue#L143), which is what we use to determine which chapter is currently active (and therefore which ToC entry is highlighted). Maybe playing around with this logic may also fix the problem?

The previous `top` value calculation was just added [about a month ago](https://github.com/ramp4-pcar4/story-ramp/pull/502) to fix an issue where clicking on a ToC entry wouldn't take the user to the top of a slide, which this new calculation re-introduces.
</blockquote></details>

Donethanks. I decided to set the `offset` property (which has default value of 0.5) to 0.1. This causes a slide change to be detected when the top border of a slide crosses the 10% mark of the screen.


<!-- Sent from Reviewable.io -->

2025-01-10 15:10 UTC, yileifeng requested changes
Testing against both the horizontal ToC (https://ramp4-pcar4.github.io/story-ramp/toc-mismatch/#/en/00000000-0000-0000-0000-000000000000) and vertical ToC (https://ramp4-pcar4.github.io/story-ramp/toc-mismatch/#/fr/00000000-0000-0000-0000-000000000000), clicking on a ToC item scrolls to the correct section but highlights the wrong item.

> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/516#-:-OGFjVfK4mWJMdRVsecH:bo8blwf)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @RyanCoulsonCA)



<!-- Sent from Reviewable.io -->

2025-01-13 19:59 UTC, IshavSohal reviewed
Donethanks, set the offset to 0.2 now, it seems to be working on my end but let me know if there's still issues

> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/516#-:-OGWEkdd7oP6ARpBpB3t:b-6eoquq)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @RyanCoulsonCA)



<!-- Sent from Reviewable.io -->

2025-01-13 20:39 UTC, yileifeng approved these changes
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/516)* status: all files reviewed, 1 unresolved discussion (waiting on @RyanCoulsonCA)



<!-- Sent from Reviewable.io -->

2025-01-13 20:44 UTC, RyanCoulsonCA reviewed
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/516)* status: all files reviewed, 1 unresolved discussion (waiting on @IshavSohal)



<!-- Sent from Reviewable.io -->

2025-01-13 20:44 UTC, RyanCoulsonCA approved these changes
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/516)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @IshavSohal)



<!-- Sent from Reviewable.io -->

2025-01-14 15:38 UTC, merged