Add support for ToC sublists
ramp4-pcar4/story-ramp pull request #520
Opened 2024-12-18 20:39 UTC by yileifeng

### Related Item(s)
Closes #492 

### Changes
- [FEATURE] adds config option for users to customize Storylines table of contents structure including submenus

### Testing
For horizontal ToC: https://ramp4-pcar4.github.io/story-ramp/toc-sublists/#/en/00000000-0000-0000-0000-000000000000

For vertical ToC: https://ramp4-pcar4.github.io/story-ramp/toc-sublists/#/fr/00000000-0000-0000-0000-000000000000

2024-12-19 17:09 UTC, RyanCoulsonCA requested changes
Looks great and works from an accessibility perspective as well!

The table of contents config doesn't seem to be respected on mobile. I think these changes also need to be in the `mobile-menu` component?

> Reviewed 4 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/520#-:-OEUokSp9kV9CGh65zMv:bz5oblj)* status: 4 of 7 files reviewed, 4 unresolved discussions (waiting on @yileifeng)

___
*[`src/components/story/chapter-menu.vue` line 156 at r1](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/520#-OEUpU9m9pareXepCXit:-OEUpU9m9pareXepCXiu:b6cb60k) ([raw file](https://github.com/ramp4-pcar4/story-ramp/blob/cdc26f9fd7b285ef337f027bf96fd2643a97db00/src/components/story/chapter-menu.vue#L156)):*
> ```Vue
>                     }"
>                 >
>                     <div class="flex">
> ```

Feel free to shut this down if I'm missing something, but I think we could simplify this component by breaking out the code inside this `flex` div into its own reusable component.

Currently, the `plugin` and `not plugin` blocks are repeated three times: once when there is no ToC config, and twice more when a ToC config exists (once for the main chapter and once for sub-chapters). By moving this repeating block into its own component, we could significantly reduce redundancy and make the code more manageable.

(definitely did not ask ChatGPT to clarify my words ^)
___
*[`src/components/story/chapter-menu.vue` line 223 at r1](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/520#-OEUsg1j8TPzLf6AdlGq:-OEUsg1j8TPzLf6AdlGr:bkv7jjq) ([raw file](https://github.com/ramp4-pcar4/story-ramp/blob/cdc26f9fd7b285ef337f027bf96fd2643a97db00/src/components/story/chapter-menu.vue#L223)):*
> ```Vue
>                         </router-link>
> 
>                         <button
> ```

This button will need an `aria-label`
___
*[`src/components/story/horizontal-menu.vue` line 50 at r1](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/520#-OEUsDV03vdXbxhIuXCP:-OEUsDV03vdXbxhIuXCQ:b-w8wd5z) ([raw file](https://github.com/ramp4-pcar4/story-ramp/blob/cdc26f9fd7b285ef337f027bf96fd2643a97db00/src/components/story/horizontal-menu.vue#L50)):*
> ```Vue
>                     }"
>                 >
>                     <div class="flex">
> ```

Same comment as the last file for this, since we're repeating it 3 times here as well we can make this file a lot cleaner by reusing the component.
___
*[`src/components/story/horizontal-menu.vue` line 87 at r1](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/520#-OEUsbrT2vB3ii0DvrNm:-OEUsbrT2vB3ii0DvrNn:bf2jqw8) ([raw file](https://github.com/ramp4-pcar4/story-ramp/blob/cdc26f9fd7b285ef337f027bf96fd2643a97db00/src/components/story/horizontal-menu.vue#L87)):*
> ```Vue
>                         </router-link>
> 
>                         <button class="mr-2" v-if="item.sublist && item.sublist.length" @click="toggleSublist(idx)">
> ```

Same as above, `aria-label`


<!-- Sent from Reviewable.io -->

2024-12-20 19:46 UTC, yileifeng reviewed
Good catch, mobile menu should have the changes integrated as well now

> Reviewed 3 of 7 files at r1, 8 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/520#-:-OE__P7OAPqOf0Y2m_WO:b-5ffz74)* status: all files reviewed, 4 unresolved discussions (waiting on @RyanCoulsonCA)

___
*[`src/components/story/chapter-menu.vue` line 156 at r1](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/520#-OEUpU9m9pareXepCXit:-OE_aP650pMJvQjgTsPn:bicalgj) ([raw file](https://github.com/ramp4-pcar4/story-ramp/blob/cdc26f9fd7b285ef337f027bf96fd2643a97db00/src/components/story/chapter-menu.vue#L156)):*
<details><summary><i>Previously, RyanCoulsonCA (Ryan Coulson) wrote…</i></summary><blockquote>

Feel free to shut this down if I'm missing something, but I think we could simplify this component by breaking out the code inside this `flex` div into its own reusable component.

Currently, the `plugin` and `not plugin` blocks are repeated three times: once when there is no ToC config, and twice more when a ToC config exists (once for the main chapter and once for sub-chapters). By moving this repeating block into its own component, we could significantly reduce redundancy and make the code more manageable.

(definitely did not ask ChatGPT to clarify my words ^)
</blockquote></details>

Good point, I added a helper component and refactored all three menu components to utilize this. Code is a lot cleaner, but have to believe that if this is possible then we should also explore refactoring all three components into one.
___
*[`src/components/story/chapter-menu.vue` line 223 at r1](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/520#-OEUsg1j8TPzLf6AdlGq:-OE_alIT859tFrnOaljA:bah2568) ([raw file](https://github.com/ramp4-pcar4/story-ramp/blob/cdc26f9fd7b285ef337f027bf96fd2643a97db00/src/components/story/chapter-menu.vue#L223)):*
<details><summary><i>Previously, RyanCoulsonCA (Ryan Coulson) wrote…</i></summary><blockquote>

This button will need an `aria-label`
</blockquote></details>

Donethanks


<!-- Sent from Reviewable.io -->

2024-12-31 15:54 UTC, RyanCoulsonCA approved these changes
Changes look good!

This is not very important, but I think the padding/margin for vertical ToC sub-lists can be reduced slightly to allow for more text to appear (removed `m-4` from the first sub-list vs left as-is for the second one):
![image.png](https://files.reviewableusercontent.io/images/reviewable/25874602/f7HOAjlX6Yo1il2PUUjVzo_y/image.png)

> Reviewed 8 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/520#-:-OFSPdTe3GIjbuYidY2n:bmueiuv)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yileifeng)

___
*[`src/components/story/chapter-menu.vue` line 156 at r1](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/520#-OEUpU9m9pareXepCXit:-OFSPA-xDMtNVyBRQE07:b-3weqpr) ([raw file](https://github.com/ramp4-pcar4/story-ramp/blob/cdc26f9fd7b285ef337f027bf96fd2643a97db00/src/components/story/chapter-menu.vue#L156)):*
<details><summary><i>Previously, yileifeng (Yi Lei Feng) wrote…</i></summary><blockquote>

Good point, I added a helper component and refactored all three menu components to utilize this. Code is a lot cleaner, but have to believe that if this is possible then we should also explore refactoring all three components into one.
</blockquote></details>

:thumbsup: <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 


<!-- Sent from Reviewable.io -->

2024-12-31 16:45 UTC, yileifeng reviewed
Good idea, kept the margin only for vertical TOC parent items

> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/520#-:-OFSalO38kgyl20-GZzC:b-5z7e2d)* status: 3 of 11 files reviewed, all discussions resolved (waiting on @RyanCoulsonCA)



<!-- Sent from Reviewable.io -->

2025-01-03 14:23 UTC, spencerwahl requested changes
![image.png](https://files.reviewableusercontent.io/images/reviewable/8732588/ropSd3g_E1fivgbU03P1oXTo/image.png)

Should the menus close when the user clicks elsewhere (or moves keyboard focus out of the menu)? Right now you can open all of the sublists and they all stay open while you do other things.

> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/520#-:-OFgXg4bAzigl32p_WUt:b1acwq9)* status: 3 of 11 files reviewed, all discussions resolved (waiting on @RyanCoulsonCA and @yileifeng)



<!-- Sent from Reviewable.io -->

2025-01-03 17:36 UTC, yileifeng reviewed
Thanks should be fixed now, menus close after mouse clicking elsewhere or when focus is off the ToC item for keyboard users. Let me know if current behavior is accurate or there are more cases I missed. 

> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/520#-:-OFhD_bv4LZaCWjAtdx1:bu0tukk)* status: 2 of 11 files reviewed, all discussions resolved (waiting on @RyanCoulsonCA)



<!-- Sent from Reviewable.io -->

2025-01-03 17:37 UTC, yileifeng reviewed
Also given that there can only be one submenu open for horizontal ToC, I refactored the component to only track the index of the dropdown that is toggled instead of tracking all items keys.

> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/520#-:-OFhEIihAJ-J0K2krg4y:b-e445tz)* status: 2 of 11 files reviewed, all discussions resolved (waiting on @RyanCoulsonCA)



<!-- Sent from Reviewable.io -->

2025-01-03 18:07 UTC, spencerwahl reviewed
Looks good to me :+1: 

> Reviewed 3 of 7 files at r1, 8 of 8 files at r5.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/520#-:-OFhLJERCXSOCMvc9V9F:b-j84sen)* status: 7 of 11 files reviewed, all discussions resolved (waiting on @RyanCoulsonCA and @yileifeng)



<!-- Sent from Reviewable.io -->

2025-01-03 18:20 UTC, spencerwahl approved these changes
> Reviewed 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/story-ramp/520)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yileifeng)



<!-- Sent from Reviewable.io -->

2025-01-03 19:09 UTC, merged